apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-vl-1
  namespace: myapp
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mariadb-pv-1
  persistentVolumeReclaimPolicy: Recycle
