#!/bin/sh


rm msgsender.tar

version=latest
if [ $# -eq 1 ]
  then
    version=$1
fi

IMAGENAME=mycluster.icp:8500/kafka/msgsender:$version
#gradle build && gradle build war
docker build -t $IMAGENAME .
docker save -o msgsender.tar $IMAGENAME
scp msgsender.tar root@10.10.80.172:/root/mjkong/msgsender
#docker push mycluster.icp:8500/semi/sender:$version
